export const Categories = [
  { id: 'all', label: 'All' },
  { id: '1', label: 'Film/Animation' },
  { id: '2', label: 'Autos/Vehicles' },
  { id: '10', label: 'Music' },
  { id: '15', label: 'Pets/Animals' },
  { id: '17', label: 'Sports' },
  { id: '20', label: 'Gaming' },
  { id: '22', label: 'People/Blogs' },
  { id: '23', label: 'Comedy' },
  { id: '24', label: 'Entertainment' },
  { id: '25', label: 'News/Politics' },
  { id: '26', label: 'How-to/Style' },
  { id: '27', label: 'Education' },
  { id: '28', label: 'Science/Technology' },
  { id: '29', label: 'Nonprofits/Activism' },
]